baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = ""
theme = "anatole"
summarylength = 20
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-159597246-1"

[params]
title = "Datarush"
author = "Datarush"
description = "Provide data driven solutions for the financial sector. Make data work for you!"
profilePicture = "images/avatar.png"
keywords = ["asset management", "data analytics", "data science", "python", "powerbi", "dashboard", "pensioenfondsen", "dekkingsgraad"]
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jeroen-van-de-erve/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/jeroen84/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:jeroen@datarush.nl"

[[params.socialIcons]]
icon = "fa-telegram"
title = "telegram"
url = "https://t.me/jeroenvde"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
