name: Website upload

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.127.0'
          extended: true

      - name: Build site
        run: hugo

      - name: Install lftp
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install lftp
  
      - name: Upload to ftp server
        run: lftp -e "set sftp:auto-confirm yes;set ssl:verify-certificate no;mirror -c -R -X *.do-not-remove public HTML;quit" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; exit
