name: oni.nl upload

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        # with:
        #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.65.3'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: SSH deploy 
        uses: garygrossgarten/github-action-scp@release
        with:
<<<<<<< HEAD
          local: ./public
          remote: HTML
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
=======
          host: ${{ secrets.FTP_ADDRESS }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./public"
          remoteDir: "/HOME"
>>>>>>> 3231aa79be8969b4a92e850452c09268db79423a
